const memberList = [
  {
    name:    'Carrie Beaird, LPC-S, LCDC',
    image:   require('../images/headshots/carrie-beaird.jpg'),
    license: [
      'Licensed Professional Counselor-Supervisor',
      'Licensed Chemical Dependency Counselor',
    ],
    website:  ['co-parentingsolutions.com', 'cbcounseling.com'],
    email:    'cbcparenting@aol.com',
    phone:    '972-448-8797',
    services: [
      'Parenting Facilitation',
      'Parent Coordination',
      'Court Ordered Therapy',
      'Reunification Therapy',
      'Substance Abuse Evaluations',
    ],
  },
  {
    name:     'Christy Bradshaw Schmidt, LPC',
    image:    require('../images/headshots/christy-schmidt.jpg'),
    license:  ['Licensed Professional Counselor'],
    website:  ['txfamilylawforensics.com'],
    email:    'christy@txfamilylawforensics.com',
    phone:    '214-502-7224',
    services: [
      'Expert Witness',
      'Reviewing Testifying Expert',
      'Forensic Consultant',
      'Child Custody Evaluations',
      'Adoption Evaluations',
    ],
  },
  {
    name:     'Holly Winter Duke, MS, LPC, NCC',
    image:    null,
    license:  ['Licensed Professional Counselor'],
    website:  ['lewisvillecounselingservices.com'],
    email:    'hduke@lewisvillecounselingservices.com',
    phone:    '469-645-1375',
    services: [
      'Court Ordered Therapy',
      'Individual Therapy (ages 10 and up)',
      'Family Therapy',
      'Co-Parenting Support and Education',
    ],
  },
  {
    name:     'Susan Fletcher, Ph.D.',
    image:    require('../images/headshots/susan-fletcher.jpeg'),
    license:  ['Licensed Psychologist'],
    website:  ['FletcherPhD.com'],
    email:    'DrFletcher@FletcherPhD.com',
    phone:    '972-612-1188',
    services: [
      'Child Custody Evaluations',
      'Psychological Evaluations',
      'Reviewing Testifying Expert',
      'Expert Witness',
      'Forensic Consultant',
      'Reunification Therapy',
      'Court Ordered Therapy',
    ],
  },
  {
    name:     'Michael Flynn, J.D., Ph.D.',
    image:    require('../images/headshots/michael-flynn.jpg'),
    license:  ['Psychologist/Attorney'],
    website:  ['michaelflynnjdphd.com'],
    email:    'docmflynn@michaelflynnjdphd.com',
    phone:    '682-990-6246',
    services: [
      'Licensing Board Defense',
      'Subpoena Assistance',
      'Deposition Assistance',
      'Business Entities',
      'Family Law Matters',
      'Wills',
    ],
  },
  {
    name:     'Gina Galloway, Ph.D., LPC-S',
    image:    require('../images/headshots/gina-galloway.jpeg'),
    license:  ['Licensed Professional Counselor-Supervisor'],
    website:  ['gallowaycounseling.com'],
    email:    'gina@ginagalloway.com',
    phone:    '817-932-3105',
    services: [
      'Court Ordered Therapy',
      'Expert Witness',
      'Play Therapy',
      'Family Therapy',
      'Co-Parenting Support and Education',
    ],
  },
  {
    name:     'Victoria Harvey, Ph.D., MSCJ',
    image:    require('../images/headshots/victoria-harvey.jpg'),
    license:  ['Licensed Psychologist'],
    website:  ['mitchellphd.com'],
    email:    'drvictoriaharvey@gmail.com',
    phone:    '972-330-7944',
    services: [
      'Psychological Evaluations',
      'Child Custody Evaluations',
      'Court Ordered Therapy',
      'Expert Witness',
      'Forensic Consultant',
    ],
  },
  {
    name:     'Steven E “Jake” Jacobson',
    image:    require('../images/headshots/jake-jacobson.jpg'),
    license:  ['Licensed Clinical Social Worker'],
    website:  ['ccdcounseling.com'],
    email:    'jake@ccdcounseling.com',
    phone:    '940-314-3444',
    services: [
      'Mediation',
      'Parenting Plan Design/Consultation',
      'Co-Parent Education',
      'Co-Parent Support',
      'Counseling',
    ],
  },
  {
    name:     'Jennifer Leister, LPC-S',
    image:    require('../images/headshots/jennifer-leister.jpg'),
    license:  ['Licensed Professional Counselor-Supervisor'],
    website:  ['Jennifercounseling.com'],
    email:    null,
    phone:    '469-828-4603',
    services: [
      'Court Ordered Therapy',
      'Reunification Therapy',
      'Collaborative Law-MHP and CS',
      'Parent Coordination',
      'Parenting Facilitation',
      'Expert Witness',
      'Forensic Consultant',
    ],
  },
  {
    name:     'Jane Phillips, Ph.D., LCSW-S',
    image:    require('../images/headshots/jane-philips.jpeg'),
    license:  ['Licensed Clinical Social Worker-Supervisor'],
    website:  ['drjanephillips.com'],
    email:    'janephillips@drjanephillips.com',
    phone:    '682-225-6990',
    services: [
      'Court Ordered Therapy',
      'Pre-divorce Parent Consultation',
      'Co-Parent Education',
      'Reunification Therapy',
      'Expert Witness',
      'Forensic Consultant',
    ],
  },
  {
    name:     'Aaron Robb, Ph.D., LPC-S',
    image:    require('../images/headshots/aaron-robb.png'),
    license:  ['Licensed Professional Counselor-Supervisor'],
    website:  ['TexasCounseling.org'],
    email:    null,
    phone:    '972-360-7437',
    services: [
      'Child Custody Evaluations',
      'Adoption Evaluations',
      'Guardian Ad Litem Appointments',
      'Adult & Family Therapy',
      'Parenting Facilitation',
      'Supervised Visitation',
      'Expert Witness',
      'Forensic Consultant',
    ],
  },
];

export default memberList;
