const memberList = [
  {
    name:     'Carrie Beaird',
    image:    null,
    license:  'License',
    website:  'Website',
    email:    'Email',
    phone:    'Phone',
    services: [
      'Service 1',
      'Service 2',
      'Service 3',
      'Service 4',
      'Service 5',
    ],
  },
  {
    name:     'Christy Bradshaw Schmidt, LPC',
    image:    require('../images/headshots/christy-schmidt.jpg'),
    license:  'Licensed Professional Counselor',
    website:  'txfamilylawforensics.com',
    email:    'christy@txfamilylawforensics.com',
    phone:    '214-502-7224',
    services: [
      'Expert Witness',
      'Reviewing Testifying Expert',
      'Forensic Consultant',
      'Child Custody Evaluations',
      'Adoption Evaluations',
    ],
  },
  {
    name:     'Holly Duke',
    image:    null,
    license:  'License',
    website:  'Website',
    email:    'Email',
    phone:    'Phone',
    services: [
      'Service 1',
      'Service 2',
      'Service 3',
      'Service 4',
      'Service 5',
    ],
  },
  {
    name:     'Susan Fletcher, Ph.D.',
    image:    require('../images/headshots/susan-fletcher.jpeg'),
    license:  'Licensed Psychologist',
    website:  'FletcherPhD.com',
    email:    'DrFletcher@FletcherPhD.com',
    phone:    '972-612-1188',
    services: [
      'Child Custody Evaluations',
      'Psychological Evaluations',
      'Reviewing Testifying Expert',
      'Expert Witness',
      'Forensic Consultant',
      'Reunification Therapy',
      'Court-Ordered Therapy',
    ],
  },
  {
    name:     'Michael Flynn, J.D., Ph.D.',
    image:    null,
    license:  'Psychologist/Attorney',
    website:  'michaelflynnjdphd.com',
    email:    'docmflynn@michaelflynnjdphd.com',
    phone:    '682-990-6246',
    services: [
      'Licensing Board Defense',
      'Subpoena Assistance',
      'Deposition Assistance',
      'Business Entities',
      'Family Law Matters',
      'Wills',
    ],
  },
  {
    name:     'Gina Galloway',
    image:    require('../images/headshots/gina-galloway.jpeg'),
    license:  'License',
    website:  'Website',
    email:    'Email',
    phone:    'Phone',
    services: [
      'Service 1',
      'Service 2',
      'Service 3',
      'Service 4',
      'Service 5',
    ],
  },
  {
    name:     'Victoria Harvey, Ph.D., MSCJ',
    image:    require('../images/headshots/victoria-harvey.jpg'),
    license:  'Licensed Psychologist',
    website:  'mitchellphd.com',
    email:    'drvictoriaharvey@gmail.com',
    phone:    '972-330-7944',
    services: [
      'Psychological Evaluations',
      'Child Custody Evaluations',
      'Court-Ordered Therapy',
      'Expert Witness',
      'Forensic Consultation',
    ],
  },
  {
    name:     'Jake Jacobson',
    image:    null,
    license:  'License',
    website:  'Website',
    email:    'Email',
    phone:    'Phone',
    services: [
      'Service 1',
      'Service 2',
      'Service 3',
      'Service 4',
      'Service 5',
    ],
  },
  {
    name:     'Jennifer Leister, LPCS',
    image:    require('../images/headshots/jennifer-leister.jpg'),
    license:  'Licensed Professional Counselor and Supervisor',
    website:  'Jennifercounseling.com',
    email:    null,
    phone:    '469-828-4602',
    services: [
      'Court-Ordered Therapy',
      'Reunification Therapy',
      'Collaborative Law-MHP and CS',
      'Parent Coordination',
      'Parent Facilitation',
      'Expert Witness',
      'Forensic Consultant',
    ],
  },
  {
    name:     'Jane Phillips',
    image:    null,
    license:  'License',
    website:  'Website',
    email:    'Email',
    phone:    'Phone',
    services: [
      'Service 1',
      'Service 2',
      'Service 3',
      'Service 4',
      'Service 5',
    ],
  },
  {
    name:     'Aaron Robb',
    image:    require('../images/headshots/aaron-robb.png'),
    license:  'License',
    website:  'Website',
    email:    'Email',
    phone:    'Phone',
    services: [
      'Service 1',
      'Service 2',
      'Service 3',
      'Service 4',
      'Service 5',
    ],
  },
];

export default memberList;
